SUCCESS_THRESHOLD_translation_ERR_MAX_CM: 0.01  # 0.1mm
SUCCESS_THRESHOLD_translation_ERR_MAX_MM: SUCCESS_THRESHOLD_translation_ERR_MAX_CM * 10
SUCCESS_THRESHOLD_rotation_ERR_MAX_DEG: 0.1  #
SUCCESS_THRESHOLD_mjac_CM:  2  # for prismatic joints
SUCCESS_THRESHOLD_mjac_DEG:  3  # for revolute joints
