[tool.poetry]
name = "cppflow"
version = "0.1.0"
description = ""
authors = ["Jeremy Morgan <jsmorgan6@gmail.com>", "David Millard <dmillard@gmail.com>"]
license = "MIT"
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.poetry.dependencies]
python = ">=3.8.0,<=3.8.19"
jrl = { git = "https://github.com/jstmn/jrl.git", rev = "590234f0f5275a4568a1b0b779b9e36536d5789d" }
ikflow = { git = "https://github.com/jstmn/ikflow.git", rev = "36d0bcded760d19320a4fe0f051532a6cb5f2816" }
matplotlib = "3.7.0"
psutil = "5.9.8"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pylint = "^2.16.2"
matplotlib = "^3.7.0"
pandas = "1.5.3"
tabulate = "0.9.0"
pytest = "8.2.0"